sudo: required
services:
  - docker

before_install:
  - docker build -t sandip_nup/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run sandip_nup/react-test npm test -- --coverage


after_success:
  - docker build -t sandip_nup/multi-client ./client
  - docker build -t sandip_nup/multi-nginx ./nginx
  - docker build -t sandip_nup/multi-server ./server
  - docker build -t sandip_nup/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to dockerhub
  - docker push sandip_nup/multi-client
  - docker push sandip_nup/multi-nginx 
  - docker push sandip_nup/multi-server 
  - docker push sandip_nup/multi-worker 
